[project]
authors = ["Brian Grenier <grenierb96@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "Kelvin"
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]
version = "0.1.0"

[tasks]
test_reject = { cmd = "python3 ./scripts/run_reject_tests.py", depends-on=["package"] }
test = { cmd = "mojo test", depends-on=["generate_tests", "format_quiet", "test_reject"] }
format = "mojo format -l 80 kelvin test"
format_quiet = "magic run format -q"
package = "mojo package kelvin -o kelvin.mojopkg"
generate_tests = "python3 ./scripts/generate_tests.py"


[dependencies]
max = ">=25.2.0.dev2025031805,<26"

[environments]
default = { solve-group = "default" }
proof = { features = ["proof"], solve-group = "default" }

[feature.proof.tasks]
run_proofs = "python3 ./misc/ratio_add_proof.py"

[feature.proof.pypi-dependencies]
z3-solver = ">=4.14.1.0, <5"
