[project]
authors = ["Brian Grenier <grenierb96@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "Kelvin"
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]
version = "0.1.0"

[tasks]
test = "mojo test"
format = "mojo format -l 80 kelvin test"

[dependencies]
max = ">=25.2.0.dev2025031805,<26"
