name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml
  lint:
    uses: ./.github/workflows/pre_commit.yml
  package:
    uses: ./.github/workflows/package.yml
