name: Build the package

on:
  workflow_call:

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Run the package command
          run: |
            curl -fsSL https://pixi.sh/install.sh | sh
            export PATH="$HOME/.pixi/bin:$PATH"
            pixi run package